[package]
edition = "2018"
name = "dotup"
version = "0.1.0"

[dependencies]
log = "0.4"
serde = { version = "*", features = ["derive"] }
thiserror = "1.0"
toml = "0.5"
slotmap = "1.0"

[dev-dependencies]
tempfile = "3.2"
