[package]
edition = "2018"
name = "dotup"
version = "0.1.0"

[dependencies]
log = "*"
serde = { version = "*", features = ["derive"] }
thiserror = "*"
toml = "*"
slotmap = "*"

[dev-dependencies]
tempfile = "3.2"
