[package]
name = "dotup"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = { version = "3.1.3", features = ["derive"] }
anyhow = "1.0.55"
flexi_logger = "0.22.3"
log = "0.4.16"
serde = { version = "1.0.136", features = ["derive"] }
slotmap = "1.0.6"
thiserror = "1.0.30"
toml = "0.5.8"
