[package]
edition = "2018"
name = "dotup_cli"
version = "0.1.0"

[[bin]]
name = "dotup"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = "*"
clap = "3.0.0-beta.2"
log = "*"

[dependencies.dotup]
path = "../dotup"

[dependencies.flexi_logger]
features = ["colors"]
version = "*"

[dev-dependencies]
tempfile = "3.2"
assert_cmd = "1.0"
